config/routes.rb
Rails.application.routes.draw do
  root 'tokens#index'
  resources :tokens
end

app/models/token.rb
class Token < Asset

  def get_ticks_minute qty
    p "Get minute Tick (#{qty})..."

    t = Cryptocompare::HistoMinute.find(self.sym, 'USD', {'limit' => qty})['Data']
    d = 1.minute.to_i

    create_ticks t, d

    p 'Done!'
  end

  def get_ticks_hour qty
    p "Get Ticks Hour (#{qty})..."

    d = 1.hour.to_i
    h = Cryptocompare::HistoHour.find(self.sym, 'USD', {'limit' => qty})

    p h['Data']

    create_ticks h['Data'], d

    p 'Done!'
  end

  def get_ticks_day qty
    p "Get Ticks Day (#{qty})..."

    t = Cryptocompare::HistoDay.find(self.sym, 'USD', {'limit' => qty})
    create_ticks t['Data'], 1.day.to_i

    p 'Done!'
  end

  def set_fixed_values
    cc = Cryptocompare::Price.full(self.sym, 'USD')
    cc = cc["RAW"][self.sym]["USD"]
    self.price_usd = cc['PRICE']
    self.market_cap_usd = cc['MKTCAP']
    self.available_supply = cc['SUPPLY']
    self.percent_change_24h = self.get_percent_change_24h(self.price_usd)
    self.percent_change_7d = self.get_percent_change_7d(self.price_usd)
    self.save
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all.order(market_cap_usd: -1)
    @stocks = Stock.all.order(market_cap_usd: -1)

    @market_cap = TokenMarketCap.instance.ticks.day
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
    cc = Cryptocompare::Price.full(@token.sym, 'USD')
    cc = cc["RAW"][@token.sym]["USD"]
    @current = {}
    @current[:price] = cc["PRICE"]
    @current[:change] = cc["CHANGEPCT24HOUR"]

    @ticks = @token.ticks.where(
      :created_at.lte => Time.now
    )
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:name, :sym)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_chart.html.erb
<div id="<%= chart_id %>" style="width: 100%; height: 500px;"></div>

<script>
  google.charts.load('current', {packages: ['corechart', 'line']});
  google.charts.setOnLoadCallback(drawLineColors);

  function drawLineColors() {
    var data = new google.visualization.DataTable();
    data.addColumn('date', 'X');
    data.addColumn('number', 'Price');
    data.addColumn('number', 'Leading Span A');
    data.addColumn('number', 'Leading Span B');

    data.addRows([
      <% ticks.each do |t| %>
        [
          new Date('<%= t.created_at.rfc2822 %>'),
          <%= t.open %>,
          <%= t.leading_span_a || 0 %>,
          <%= t.leading_span_b || 0 %>
        ],
      <% end %>
    ]);

    var options = {
      hAxis: {title: 'Time'},
      vAxis: {title: 'Price'},
      colors: ['#a52714', '#097138', '#4141ef']
    };

    var chart = new google.visualization.LineChart(document.getElementById('<%= chart_id %>'));
    chart.draw(data, options);
  }
</script>

app/views/tokens/_form.html.erb
<%= form_with(model: token, local: true) do |form| %>
  <% if token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :token_name %>
  </div>

  <div class="field">
    <%= form.label :sym %>
    <%= form.text_field :sym, id: :token_sym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tokens/_main_table.html.slim
table.table
  thead
    tr
      th colspan="4"
      th colspan="2"
        center Change
      th colspan="3"
        center Moving Averages
      th colspan="3"
        center Ichimoku Cloud
      th
    tr
      th Token
      th Symbol
      th Price
      th Market Cap
      th
        center 24H
      th
        center 7D
      th
        center 21D
      th
        center 50D
      th
        center 200D
      th
        center H
      th
        center D
      th
        center W
      th
        center 7D

  tbody
    =  render tokens

app/views/tokens/_market_cap.html.erb
<p>
  Whole Market:
  $<%= number_with_precision(@market_cap.first.open, precision: 0, delimiter: ',') %>
</p>

<%= render 'chart', chart_id: 'chart_hour', ticks: @market_cap %>

app/views/tokens/_mini_chart.html.erb
<div id="<%= chart_id %>" style="width: 140px; height: 100px;"></div>

<script>
  google.charts.load('current', {packages: ['corechart', 'line']});
  google.charts.setOnLoadCallback(drawBasic);

  function drawBasic() {
    var data = new google.visualization.DataTable();
    data.addColumn('date', null);
    data.addColumn('number', null);

    data.addRows([
      <% ticks.each_with_index do |t, i| %>
        [
          new Date('<%= t.created_at.rfc2822 %>'),
          <%= t.close %>
        ],
      <% end %>
    ]);

    var options = {
      hAxis: {
        textPosition: 'none',
        gridlines: { count: 0 }
      },
      vAxis: {
        textPosition: 'none',
        gridlines: { count: 0 }
      },
      legend: 'none',
      chartArea: {width: '90%', height: '90%'}
    };

    var chart = new google.visualization.LineChart(document.getElementById('<%= chart_id %>'));
    chart.draw(data, options);
  }
</script>

app/views/tokens/_status_bar.html.erb
<div class="status_bar">
  <div
    class="<%= status %>"
    style="
      height: <%= (opacity * 10) > 49 ? 49 : (opacity * 10) %>px;
      opacity: <%= opacity / 5 %>;
    ">
  </div>
</div>

app/views/tokens/_token.html.slim
tr
  / td = link_to token.name, token
  td = token.name
  td = token.sym
  td = "$#{number_with_precision(token.price_usd, precision: 2, delimiter: ',')}"
  td = "#{number_with_precision(token.market_cap_usd / 1000000000, precision: 1, delimiter: ',')}B"
  td class="percent-change #{'positive' if token.percent_change_24h.positive?}"
    = "#{number_with_precision(token.percent_change_24h * 100, precision: 2)}%"
  td class="percent-change #{'positive' if token.percent_change_7d.positive?}"
    = "#{number_with_precision(token.percent_change_7d * 100, precision: 2)}%"
  td
    = render 'status_bar', token: token, status: token.ma_status_21, opacity: token.ma_21_opacity
  td
    = render 'status_bar', token: token, status: token.ma_status_50, opacity: token.ma_50_opacity
  td
    = render 'status_bar', token: token, status: token.ma_status_200, opacity: token.ma_200_opacity
  td
    = render 'status_bar', token: token, status: token.cloud_status_hour, opacity: token.cloud_status_hour_opacity
  td
    = render 'status_bar', token: token, status: token.cloud_status_day, opacity: token.cloud_status_day_opacity
  td
    = render 'status_bar', token: token, status: token.cloud_status_week, opacity: token.cloud_status_week_opacity
  td
    = render 'mini_chart', chart_id: "#{token.sym}_chart", ticks: token.ticks.hour.limit(1) + token.ticks.day.limit(7)

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.slim
.container
  p
    h2 Token Scanner
  p = "Last Updated: #{@tokens.first.ticks.first.created_at}"

  br

  = render 'main_table', tokens: @tokens

  br

  = render 'main_table', tokens: @stocks

  br

  / = render 'market_cap'

  br

  / = link_to 'New Token', new_token_path

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.slim
.container

  h2
    = link_to 'Token Scanner', root_path

  br

  = render 'main_table', tokens: [@token]

  = render 'chart', chart_id: 'chart_hour', ticks: @ticks.hour

  = render 'chart', chart_id: 'chart_day', ticks: @ticks.day

  = render 'chart', chart_id: 'chart_week', ticks: @ticks.week